# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/FPGA/FPGA/Zynq7020/ram_test/ram_test.srcs/sources_1/ip/ram_ip/ram_ip.xci
# IP: The module: 'ram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/FPGA/Zynq7020/ram_test/ram_test.srcs/sources_1/ip/ram_ip/ram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Project/FPGA/FPGA/Zynq7020/ram_test/ram_test.srcs/sources_1/ip/ram_ip/ram_ip.xci
# IP: The module: 'ram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/FPGA/Zynq7020/ram_test/ram_test.srcs/sources_1/ip/ram_ip/ram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
