# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo.xci
# IP: The module: 'input_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo.xci
# IP: The module: 'input_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/FPGA/FPGA/Diploma/FPGA/FPGA.srcs/sources_1/ip/input_fifo/input_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
