set_property SRC_FILE_INFO {cfile:F:/FPGA/FPGA/pll_test/pll_test.srcs/constrs_1/new/ip_top.xdc rfile:../../../pll_test.srcs/constrs_1/new/ip_top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports clk_o]
